apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrpl-data-pipeline.fullname" . }}
  labels:
    {{- include "xrpl-data-pipeline.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xrpl-data-pipeline.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xrpl-data-pipeline.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "xrpl-data-pipeline.serviceAccountName" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- else }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: fluent-bit
          image: "{{ .Values.fluent.image.repository }}:{{ .Values.fluent.image.tag }}"
          ports:
            - name: forward
              containerPort: {{ .Values.fluent.forwardPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.fluent.httpPort }}
              protocol: TCP
            - name: http-debug
              containerPort: {{ .Values.fluent.httpDebugPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.fluent.resources | nindent 12 }}
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: fluent-bit-sa-key
              mountPath: /fluent-bit/etc/
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: fluent-bit-sa-key
          secret:
            secretName: fluent-bit-sa-key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
