version: "3.9"

services:
  fluent-bit:
    # Using specific version of the Fluent Bit image
    #
    image: "fluent/fluent-bit:2.0.8"
    volumes:
      # point the current config to the container config
      - ./fluent_config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

      # this file is not provided as part of the repository
      - ~/sa-private-key.json:/fluent-bit/etc/credentials.json

  server_container:
    build:
      context: .
      network: host
      args:
        - NETWORK=$NETWORK
        - LEDGER_INDEX_PATH=/persistent_data/ledgers.txt
    volumes:
      - ledgers:/persistent_data/
    depends_on:
      - fluent-bit
    ports:
      - "23223:23223"

volumes:
  ledgers:
