apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrpl-data-pipeline.fullname" . }}
  labels:
    {{- include "xrpl-data-pipeline.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrpl-data-pipeline.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xrpl-data-pipeline.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "xrpl-data-pipeline.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.releaseImage }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.releaseImagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: fluent-bit
          image: "{{ .Values.fluent.releaseImage }}"
          imagePullPolicy: {{ .Values.fluent.releaseImagePullPolicy }}
          ports:
            - name: forward
              containerPort: {{ .Values.fluent.forwardPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.fluent.httpPort }}
              protocol: TCP
            - name: http-debug
              containerPort: {{ .Values.fluent.httpDebugPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.fluent.resources | nindent 12 }}
          volumeMounts:
            - name: fluent-bit-secrets-and-config
              mountPath: /fluent-bit/etc/
            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml
      volumes:
        - name: fluent-bit-secrets-and-config
          projected:
            sources:
              - secret:
                  name: fluent-bit-sa-key
              - configMap:
                  name: fluent-bit-config
        - name: app-config
          configMap:
            name: app-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
