apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrpl-data-pipeline.fullname" . }}
  labels:
    {{- include "xrpl-data-pipeline.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"443":{"name": "{{ include "xrpl-data-pipeline.fullname" . }}-neg"}}}'
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "xrpl-data-pipeline.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      
