version: "3.7"

services:
  fluent-bit:
    # Using specific version of the Fluent Bit image
    #
    image: "fluent/fluent-bit:2.0.8"

    ports:
      # {host port}:{container port}
      # you can connect through 'localhost:24224'
      # port 24224 is the container port
      #
      - "24224:24224"
      - "14224:14224"
      - "25225:25225"

    volumes:
      # point the current config to the container config
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

      # this file is not provided as part of the repository
      - /home/adavoodi/sa-private-key.json:/fluent-bit/etc/credentials.json
