name: Build and deploy pipeline
on:
  push:
    branches:
      - 'main'
    # don't run this pipeline on tags; those should be reserved for releases
    tags-ignore:
      - '**'
concurrency:
  group: ${{ github.ref }}
jobs:
  pre-build:
    name: "Pre-build steps"
    uses: ./.github/workflows/pre-build.yaml

  build-and-publish:
    name: 'Build docker image and push to GCR'
    needs: [pre-build]
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      docker_image_location: ${{ needs.pre-build.outputs.docker_image_location }}

  deploy-dev:
    name: 'Deploy to Dev'
    needs: [ pre-build, build-and-publish ]
    uses: ./.github/workflows/deploy-via-gitops.yaml
    secrets: inherit
    with:
      helm_repo_url: "oci://us-central1-docker.pkg.dev/cbdc-helm-repo/ripplex-helm-charts"
      helm_chart_name: "xrpl-data-pipeline"
      helm_chart_dir: "./charts"
      short_sha: ${{ needs.pre-build.outputs.short_sha }}
      version: ${{ needs.pre-build.outputs.docker_image_tag }}
      docker_image_location: ${{ needs.pre-build.outputs.docker_image_location }}
      gitops_repository: "xpring-eng/ripplex-cbdc-gitops"
      gitops_path: "gcp/sandbox/dev/xrpl-data-pipeline/"
      gitops_dependency_name: "xrpl-data-pipeline"
